baseURL = 'https://effulgent-belekoy-b37d9e.netlify.app/'
languageCode = 'en-us'
title = 'Ryuichiro Suzuki'
theme = ["mdi", "hello-friend-ng", "cl-image"]
enableEmoji = true

[params]
  images = ["/coding-me.jpg"]
  homeSubtitle = "Fullstack Developer in Barcelona"
  enableThemeToggle = true
  customCSS = ["/css/home.css", "/css/mdi.css", "/css/image.css"]
  enableSharingButtons = true
  baseURL = "https://res.cloudinary.com/"
  cloudName = "scooter-scooter"
  folderName = "Portfolio"


[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Blogs"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "/about"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume"

[[params.social]]
  name = "twitter"
  url = "https://www.twitter.com/RyuichiroSuzuki"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ryuichiro-suzuki-scooter/"

[[params.social]]
  name = "github"
  url = "https://github.com/SuzukiRyuichiro"

[[params.social]]
  name = "fitbit"
  url = "https://www.fitbit.com/user/944WLQ"

[[params.social]]
  name = "spotify"
  url = "https://open.spotify.com/user/22ndwarmwin74uwyftti4zvla"

[params.portrait]
    path = "https://res.cloudinary.com/scooter-scooter/image/upload/v1662897240/Portfolio/coding-me.jpg"
    alt = "coding-me"
    maxWidth = "350px"

[params.logo]
  logoText = "Hi. I'm scooter"
