baseURL = 'https://ryuichirosuzuki.com'
languageCode = 'en-us'
title = 'Ryuichiro Suzuki'
theme = ["mdi", "hello-friend-ng", "cl-image", "devicons"]
enableEmoji = true
googleAnalytics = "G-8WDFLLSMBT"

[params]
images = ["/coding-me.jpg"]
description = "Ryuichiro Suzuki is a Web Developer and a cycling enthusiast in Tokyo"
homeSubtitle = "Mainly Web Developer, but does many other stuff..."
enableThemeToggle = true
customCSS = [
  "/css/home.css",
  "/css/mdi.css",
  "/css/image.css",
  "/css/video.css",
]
enableSharingButtons = true
baseURL = "https://res.cloudinary.com/"
cloudName = "scooter-scooter"
folderName = "Portfolio"


[menu]
[[menu.main]]
identifier = "posts"
name = "Blogs"
url = "/posts"
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about"
[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/ryuichirosuzuki.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/suzukiryuichiro/"

[[params.social]]
name = "github"
url = "https://github.com/SuzukiRyuichiro"

[[params.social]]
name = "strava"
url = "https://www.strava.com/athletes/53586567"

[[params.social]]
name = "spotify"
url = "https://open.spotify.com/user/22ndwarmwin74uwyftti4zvla"

[params.portrait]
path = "https://res.cloudinary.com/scooter-scooter/image/upload/v1741310924/cagobike-me.jpg"
alt = "coding-me"
maxWidth = "350px"

[params.logo]
logoText = "Hi. I'm scooter"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
