baseURL = 'https://effulgent-belekoy-b37d9e.netlify.app/'
languageCode = 'en-us'
title = 'Ryuichiro Suzuki'
theme = ["hello-friend-ng"]
enableEmoji = true

[params]
  images = ["/coding-me.jpg"]
  homeSubtitle = "Fullstack Developer in Barcelona"
  enableThemeToggle = true
  customCSS = ["/css/home.css"]
  enableSharingButtons = true


[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Blogs"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "/about"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume"

[[params.social]]
  name = "twitter"
  url = "https://www.twitter.com/RyuichiroSuzuki"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ryuichiro-suzuki-scooter/"

[[params.social]]
  name = "github"
  url = "https://github.com/SuzukiRyuichiro"

[[params.social]]
  name = "fitbit"
  url = "https://www.fitbit.com/user/944WLQ"

[[params.social]]
  name = "spotify"
  url = "https://open.spotify.com/user/22ndwarmwin74uwyftti4zvla"

[params.portrait]
    path = "/coding-me.jpg"
    alt = "coding-me"
    maxWidth = "350px"

[params.logo]
  logoText = "scooter"
